const products = [
    {
        id: 1,
        name: "Khoá học React cơ bản",
        price: 499000,
        image: require("../assets/Banners/react.png"),
        shortDesc: "Học React từ cơ bản đến nâng cao, thực hành dự án thực tế.",
        longDesc: "Khoá học này giúp bạn nắm vững React, xây dựng ứng dụng web hiện đại, tối ưu hiệu suất và dễ bảo trì. Bao gồm các chủ đề: JSX, state, props, hooks, routing, quản lý dự án, kết nối API, tối ưu hoá, và nhiều hơn nữa.",
    },
    {
        id: 2,
        name: "Tiếng Anh giao tiếp với người bản xứ",
        price: 1200000,
        image: require("../assets/Banners/ta.png"),
        shortDesc: "Luyện nói tiếng Anh với giáo viên Mỹ, Anh, Úc.",
        longDesc: "Khoá học giúp bạn tự tin giao tiếp tiếng Anh với người bản xứ, luyện phát âm, phản xạ, từ vựng và ngữ pháp thực tế. Học qua Zoom, có bài tập và feedback cá nhân.",
    },
    {
        id: 3,
        name: "Giáo trình luyện thi IELTS 7.0+",
        price: 850000,
        image: require("../assets/Banners/ta.png"),
        shortDesc: "Tài liệu luyện thi IELTS đầy đủ kỹ năng, cập nhật mới nhất.",
        longDesc: "Bộ giáo trình gồm sách, file nghe, bài tập thực hành, tips và chiến lược làm bài cho từng kỹ năng. Phù hợp tự học hoặc học cùng giáo viên.",
    },
    {
        id: 4,
        name: "Khoá học Lập trình Python cho người mới bắt đầu",
        price: 650000,
        image: require("../assets/Banners/react.png"),
        shortDesc: "Học Python từ số 0, thực hành nhiều bài tập thực tế.",
        longDesc: "Khoá học cung cấp kiến thức nền tảng về Python, giải quyết bài toán thực tế, hướng dẫn từng bước, phù hợp cho người chưa biết gì về lập trình.",
    },
    {
        id: 5,
        name: "Tài liệu Toán tư duy cho học sinh tiểu học",
        price: 320000,
        image: require("../assets/Banners/ta.png"),
        shortDesc: "Bộ tài liệu giúp trẻ phát triển tư duy logic, sáng tạo.",
        longDesc: "Tài liệu gồm bài tập, trò chơi, hướng dẫn giải chi tiết, giúp học sinh tiểu học yêu thích và học tốt môn Toán.",
    },
    {
        id: 6,
        name: "Khoá học Thiết kế UI/UX cơ bản",
        price: 780000,
        image: require("../assets/Banners/react.png"),
        shortDesc: "Học cách thiết kế giao diện người dùng đẹp và hiệu quả.",
        longDesc: "Khoá học giới thiệu về nguyên lý thiết kế UI/UX, wireframe, prototype, màu sắc, typography và sử dụng công cụ như Figma, Adobe XD.",
    },
    {
        id: 7,
        name: "Khoá học Digital Marketing 2025",
        price: 990000,
        image: require("../assets/Banners/b5.jpg"),
        shortDesc: "Nắm vững kiến thức marketing số từ A-Z.",
        longDesc: "Khoá học giúp bạn hiểu rõ về SEO, Google Ads, Facebook Ads, Email Marketing, Content Marketing và xây dựng chiến dịch hiệu quả.",
    },
    {
        id: 8,
        name: "Giáo trình luyện thi TOEIC 800+",
        price: 600000,
        image: require("../assets/Banners/b6.jpg"),
        shortDesc: "Tài liệu luyện thi TOEIC đầy đủ cấu trúc đề và mẹo làm bài.",
        longDesc: "Bộ giáo trình cập nhật format mới, luyện cả Listening và Reading, phù hợp cho sinh viên, người đi làm cần điểm TOEIC để xin việc.",
    },
    {
        id: 9,
        name: "Khoá học Java Spring Boot Fullstack",
        price: 1450000,
        image: require("../assets/Banners/react.png"),
        shortDesc: "Xây dựng ứng dụng web thực tế với Java Spring Boot.",
        longDesc: "Khoá học từ cơ bản đến nâng cao, bao gồm Spring MVC, REST API, kết nối cơ sở dữ liệu, bảo mật, triển khai ứng dụng thực tế.",
    },
    {
        id: 10,
        name: "Tự học Excel từ A-Z",
        price: 299000,
        image: require("../assets/Banners/b6.jpg"),
        shortDesc: "Thành thạo Excel cho công việc văn phòng, kế toán.",
        longDesc: "Hướng dẫn chi tiết các hàm thông dụng, xử lý bảng tính, vẽ biểu đồ, làm báo cáo và các mẹo tăng hiệu suất làm việc trên Excel.",
    },
];

export default products;
